### ISSUE TITLE
htmlifier issues

### ISSUE THREAD

**Issue by SheepTester** [SheepTester/words-go-here#1]
lists are apparently an issue?

and video sensing

**Comment by PiotrGrochowski** [comment]
http://s000.tinyupload.com/index.php?file_id=17754944288287213838

I made it restart with the space key. The problem is, the starting interface is broken: the costume relevant to the ask prompt only shows after the ask prompt, and the ask prompt doesn't have any text in it.

**Comment by SheepTester** [comment]
@PiotrGrochowski I made the ask inputs better; your project should work now

**Comment by PiotrGrochowski** [comment]
How come after fixing a single problem you close the entire issue related to  htmlifier issues? Do you reopen the issue each time someone detects another bug?

**Comment by SheepTester** [comment]
No, this issue was mostly meant for myself as a reminder, which is why the title wasn't well made and specific. I would expect a new issue if someone else finds another bug

**Comment by heiderAx** [comment]
When i uploaded Paper Minecraft to this it moves the image that follows the mouse farther away when I move it farther away from the center of the screen. The older versions didn't do this.

**Comment by SheepTester** [comment]
> When i uploaded Paper Minecraft to this it moves the image that follows the mouse farther away when I move it farther away from the center of the screen. The older versions didn't do this.

This has been fixed. In the future, it would be ideal if problems were reported in a new issue

**Comment by vinayandkitty** [comment]
Hi
When I uploaded a sb3 file with video sensing.     It didn't work
