### ISSUE TITLE
HTTP API for HTMLifier

### ISSUE THREAD

**Issue by filips123** [SheepTester/words-go-here#3]
Can you do some HTTP API for HTMLifier? With this, I mean API where you can send HTTP request and it will automatically convert and download project.

For example, if you would want to download the converted project, you would do this:

```bash
wget https://example.com/htmlifier?project=345675439&title=Example&username=&compatibility=1&turbo=0
```

Which will download the converted file automatically.

However, this probably won't be possible with GitHub Pages as they don't support backend, but you may found some other free hosting for that.

**Comment by SheepTester** [comment]
Why would this process need to be automated? Also, given Scratch's target audience, I think an API for this wouldn't benefit many people

**Comment by filips123** [comment]
I mostly want API when #4 was not fixed so I would automatically download the file and patch it using some script. But as that issue is now fixed, I don't need API anymore for this.

One other use-case would be automatic updating, but I don't know how used would it be.

**Comment by SheepTester** [comment]
> But as that issue is now fixed, I don't need API anymore for this.

Okay

> One other use-case would be automatic updating, but I don't know how used would it be.

I don't think it'd be used a lot, if at all
