### ISSUE TITLE
Custom server for username detection and cloud variables

### ISSUE THREAD

**Issue by filips123** [SheepTester/words-go-here#5]
Can you add support to detect username and store cloud variables on the custom server? For this, HTMLifier website should be modified with additional field which would specify API URL of the cloud server. That server should be hosted by the developer of the game. And when the game will be used, HTMLifier will use that API to get the player's username and get/set cloud variables.

For best compatibility, HTMLifier should support two types of APIs. First is simple HTTP GET/POST, where HTMLifier will first GET username and GET current state of cloud variables on the game start, and POST new data on every change. The other should be with WebScokets, where the same thing should be done, but via WebScokets.

**Comment by moeenio** [comment]
You can use a custom cloud server already

**Comment by filips123** [comment]
Yes, since b60d0a8.
